# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
[HealthChecksFeatures]
disable_cuda_memtest = true
disable_check_zombie = true
disable_check_dstate = true
disable_link_flap = true
disable_xid_errors = true
disable_io_errors = true
disable_proc_freq = true
disable_freq_governor = true
disable_check_mem_size = true
disable_ipmi_sel = true
disable_hca_count = true
disable_disk_usage = true
disable_disk_size = true
disable_mounted_dir = true
disable_file_exists = true
disable_dir_exists = true
disable_running_process = true
disable_check_ssh = true
disable_slurm_state = true
disable_slrmctld_count = true
disable_slurm_cluster_avail = true
disable_service_status = true
disable_package_version = true
disable_nccl_tests = true
disable_nvidia_smi = false
disable_nvidia_smi_gpu_num = true
disable_nvidia_smi_clock_freq = true
disable_nvidia_smi_running_procs = true
disable_nvidia_smi_gpu_temp = true
disable_nvidia_smi_mem_usage = true
disable_nvidia_smi_retired_pages = true
disable_nvidia_smi_ecc_uncorrected = true
disable_nvidia_smi_ecc_corrected = true
disable_nvidia_smi_row_remap = true
disable_dcgmi_diag = true
disable_dcgmi_nvlink = true
disable_dcgmi_nvlink_error = true
disable_dcgmi_nvlink_status = true
disable_check_ibstat = true
disable_check_ib_interfaces = true
disable_pass_status = true
disable_user_access_path_check = true
disable_check_uptime = true
disable_check_module = true
disable_check_clocksource = true
disable_check_sensors = true
